config/routes.rb
Paperclip::Application.routes.draw do
  resources :garment_images

  resources :sizes

  resources :garments

  resources :categories

  resources :users

   root :to => 'users#index'

end

app/models/garment.rb
class Garment < ActiveRecord::Base
  attr_accessible :brand, :price, :size_id
  
  belongs_to :size
  has_many :garment_image, :dependent => :destroy
  
  accepts_nested_attributes_for :garment_image, :reject_if => lambda { |t| t['garment_image'].nil? }
end

app/controllers/garments_controller.rb
class GarmentsController < ApplicationController
  # GET /garments
  # GET /garments.json
  def index
    @garments = Garment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @garments }
    end
  end

  # GET /garments/1
  # GET /garments/1.json
  def show
    @garment = Garment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @garment }
    end
  end

  # GET /garments/new
  # GET /garments/new.json
  def new
    @garment = Garment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @garment }
    end
  end

  # GET /garments/1/edit
  def edit
    @garment = Garment.find(params[:id])
  end

  # POST /garments
  # POST /garments.json
  def create
    @garment = Garment.new(params[:garment])

    respond_to do |format|
      if @garment.save
        format.html { redirect_to @garment, notice: 'Garment was successfully created.' }
        format.json { render json: @garment, status: :created, location: @garment }
      else
        format.html { render action: "new" }
        format.json { render json: @garment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /garments/1
  # PUT /garments/1.json
  def update
    @garment = Garment.find(params[:id])

    respond_to do |format|
      if @garment.update_attributes(params[:garment])
        format.html { redirect_to @garment, notice: 'Garment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @garment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garments/1
  # DELETE /garments/1.json
  def destroy
    @garment = Garment.find(params[:id])
    @garment.destroy

    respond_to do |format|
      format.html { redirect_to garments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/garments_helper.rb
module GarmentsHelper
end

app/views/garments/_form.html.erb
<%= form_for(@garment) do |f| %>
  <% if @garment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@garment.errors.count, "error") %> prohibited this garment from being saved:</h2>

      <ul>
      <% @garment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :size_id %><br />
     <%= f.collection_select :size_id, Size.all, :id, :name %>
  </div>
  
  
  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/garments/edit.html.erb
<h1>Editing garment</h1>

<%= render 'form' %>

<%= link_to 'Show', @garment %> |
<%= link_to 'Back', garments_path %>

app/views/garments/index.html.erb
<h1>Listing garments</h1>

<table>
  <tr>
    <th>Brand</th>
    <th>Price</th>
    <th>Size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @garments.each do |garment| %>
  <tr>
    <td><%= garment.brand %></td>
    <td><%= garment.price %></td>
    <td><%= garment.size %></td>
    <td><%= link_to 'Show', garment %></td>
    <td><%= link_to 'Edit', edit_garment_path(garment) %></td>
    <td><%= link_to 'Destroy', garment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Garment', new_garment_path %>

app/views/garments/new.html.erb
<h1>New garment</h1>

<%= render 'form' %>

<%= link_to 'Back', garments_path %>

app/views/garments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Brand:</b>
  <%= @garment.brand %>
</p>

<p>
  <b>Price:</b>
  <%= @garment.price %>
</p>

<p>
  <b>Size:</b>
  <%= @garment.size.name %>
</p>


<%= link_to 'Edit', edit_garment_path(@garment) %> |
<%= link_to 'Back', garments_path %>