config/routes.rb
Paperclip::Application.routes.draw do
  resources :garment_images

  resources :sizes

  resources :garments

  resources :categories

  resources :users

   root :to => 'users#index'

end

app/models/garment_image.rb
class GarmentImage < ActiveRecord::Base
  attr_accessible :caption, :garment_id
  
  belongs_to :garment
has_attached_file :photo,  styles: { 
		:small => '150x150#', 
		:large => '320x240#' 
	}
validates_attachment_presence :photo
validates_attachment_size :photo , :less_than => 1.megabytes
end

app/controllers/garment_images_controller.rb
class GarmentImagesController < ApplicationController
  # GET /garment_images
  # GET /garment_images.json
  def index
    @garment_images = GarmentImage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @garment_images }
    end
  end

  # GET /garment_images/1
  # GET /garment_images/1.json
  def show
    @garment_image = GarmentImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @garment_image }
    end
  end

  # GET /garment_images/new
  # GET /garment_images/new.json
  def new
    @garment_image = GarmentImage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @garment_image }
    end
  end

  # GET /garment_images/1/edit
  def edit
    @garment_image = GarmentImage.find(params[:id])
  end

  # POST /garment_images
  # POST /garment_images.json
  def create
    @garment_image = GarmentImage.new(params[:garment_image])

    respond_to do |format|
      if @garment_image.save
        format.html { redirect_to @garment_image, notice: 'Garment image was successfully created.' }
        format.json { render json: @garment_image, status: :created, location: @garment_image }
      else
        format.html { render action: "new" }
        format.json { render json: @garment_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /garment_images/1
  # PUT /garment_images/1.json
  def update
    @garment_image = GarmentImage.find(params[:id])

    respond_to do |format|
      if @garment_image.update_attributes(params[:garment_image])
        format.html { redirect_to @garment_image, notice: 'Garment image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @garment_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garment_images/1
  # DELETE /garment_images/1.json
  def destroy
    @garment_image = GarmentImage.find(params[:id])
    @garment_image.destroy

    respond_to do |format|
      format.html { redirect_to garment_images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/garment_images_helper.rb
module GarmentImagesHelper
end

app/views/garment_images/_form.html.erb
<%= form_for(@garment_image) do |f| %>
  <% if @garment_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@garment_image.errors.count, "error") %> prohibited this garment_image from being saved:</h2>

      <ul>
      <% @garment_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label : %><br />
    <%= f.text_field : %>
  </div>
  <div class="field">
    <%= f.label :garment_id %><br />
    <%= f.text_field :garment_id %>
  </div>
  <div class="field">
    <%= f.label : %><br />
    <%= f.number_field : %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/garment_images/edit.html.erb
<h1>Editing garment_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @garment_image %> |
<%= link_to 'Back', garment_images_path %>

app/views/garment_images/index.html.erb
<h1>Listing garment_images</h1>

<table>
  <tr>
    <th>Caption</th>
    <th></th>
    <th>Garment</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @garment_images.each do |garment_image| %>
  <tr>
    <td><%= garment_image.caption %></td>
    <td><%= garment_image. %></td>
    <td><%= garment_image.garment_id %></td>
    <td><%= garment_image. %></td>
    <td><%= link_to 'Show', garment_image %></td>
    <td><%= link_to 'Edit', edit_garment_image_path(garment_image) %></td>
    <td><%= link_to 'Destroy', garment_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Garment image', new_garment_image_path %>

app/views/garment_images/new.html.erb
<h1>New garment_image</h1>

<%= render 'form' %>

<%= link_to 'Back', garment_images_path %>

app/views/garment_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caption:</b>
  <%= @garment_image.caption %>
</p>

<p>
  <b>:</b>
  <%= @garment_image. %>
</p>

<p>
  <b>Garment:</b>
  <%= @garment_image.garment_id %>
</p>

<p>
  <b>:</b>
  <%= @garment_image. %>
</p>


<%= link_to 'Edit', edit_garment_image_path(@garment_image) %> |
<%= link_to 'Back', garment_images_path %>